/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interpreter;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class AppTest {
    static Brainfuck bf;
    
    @BeforeAll
    static void initBF() {
        assertDoesNotThrow(() -> { bf = new Brainfuck(); });
    }

    @ParameterizedTest
    @ValueSource(chars = {'+', '-', ',', '.', '>', '<'})
    @Tag("Every Registered Command to be Recognized")
    void inputSingleCommand(char code) {
        assertDoesNotThrow(() -> { bf.debug(String.valueOf(code)); });
    }
}
